name: Deploy hexo blog
on:
  push:
    branches:
      - "release"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "release"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm packages
        run: npm install

      - name: Check node & npm version
        run: |
          echo "Node version is $(node -v)"
          echo "npm version is $(npm -v)"

      - name: Build
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          sed -i'' "s~git@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml
          rm -rf .deploy_git
          npm install hexo-auto-category --save
          
      - name: Deploy
        run: |
          hexo clean
          hexo build
          hexo deploy
